// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

//Contact Module const
export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

//Auth const
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';

// Auth Login Check

export const USER_LOGIN_CHECK_REQUEST = 'USER_LOGIN_CHECK_REQUEST';
export const USER_LOGIN_CHECK_SUCCESS = 'USER_LOGIN_CHECK_SUCCESS';
export const USER_LOGIN_CHECK_FAILURE = 'USER_LOGIN_CHECK_FAILURE';

//Sticky
export const GET_STICKY = 'GET_STICKY';
export const NOTES_UPDATE = 'NOTES_UPDATE';
export const FETCH_ALL_NOTES_SUCCESS = 'FETCH_ALL_NOTES_SUCCESS';
export const UPDATE_ALL_NOTES_SUCCESS = 'UPDATE_ALL_NOTES_SUCCESS';

// changes Password
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

// Match List
export const MATCH_LIST_REQUEST = 'MATCH_LIST_REQUEST';
export const MATCH_LIST_SUCCESS = 'MATCH_LIST_SUCCESS';
export const MATCH_LIST_FAILURE = 'MATCH_LIST_FAILURE';

//Domian NAme 

export const DOMIAN_SETTING_BY_DOMAIN_NAME_REQUEST = 'DOMIAN_SETTING_BY_DOMAIN_NAME_REQUEST';
export const DOMIAN_SETTING_BY_DOMAIN_NAME_SUCCESS = 'DOMIAN_SETTING_BY_DOMAIN_NAME_SUCCESS';
export const DOMIAN_SETTING_BY_DOMAIN_NAME_FAILURE = 'DOMIAN_SETTING_BY_DOMAIN_NAME_FAILURE';


// Statement

export const USER_STATEMENT_REQUEST = 'USER_STATEMENT_REQUEST';
export const USER_STATEMENT_SUCCESS = 'USER_STATEMENT_SUCCESS';
export const USER_STATEMENT_FAILURE = 'USER_STATEMENT_FAILURE';



// Match Details


export const MATCH_DETAIL_REQUEST = 'MATCH_DETAIL_REQUEST';
export const MATCH_DETAIL_SUCCESS = 'MATCH_DETAIL_SUCCESS';
export const MATCH_DETAIL_FAILURE = 'MATCH_DETAIL_FAILURE';


//  userPositionByMarketId By Maekt Id 

export const USER_POSITION_BY_MARKETID_REQUEST = 'USER_POSITION_BY_MARKETID_REQUEST';
export const USER_POSITION_BY_MARKETID_SUCCESS = 'USER_POSITION_BY_MARKETID_SUCCESS';
export const USER_POSITION_BY_MARKETID_FAILURE = 'USER_POSITION_BY_MARKETID_FAILURE';

// completedFancyByMarketId

export const COMPLATED_FANCY_BY_MARKET_ID_REQUEST = 'COMPLATED_FANCY_BY_MARKET_ID_REQUEST';
export const COMPLATED_FANCY_BY_MARKET_ID_SUCCESS = 'COMPLATED_FANCY_BY_MARKET_ID_SUCCESS';
export const COMPLATED_FANCY_BY_MARKET_ID_FAILURE = 'COMPLATED_FANCY_BY_MARKET_ID_FAILURE';

//sportsBetsList

export const SPORTS_BET_LIST_REQUEST = 'SPORTS_BET_LIST_REQUEST';
export const SPORTS_BET_LIST_SUCCESS = 'SPORTS_BET_LIST_SUCCESS';
export const SPORTS_BET_LIST_FAILURE = 'SPORTS_BET_LIST_FAILURE';


// //................usER lEDEGER LIST
export const USER_LEDGER_LIST_REQUEST = 'USER_LEDGER_LIST_REQUEST';
export const USER_LEDGER_LIST_SUCCESS = 'USER_LEDGER_LIST_SUCCESS';
export const USER_LEDGER_LIST_FAILURE = 'USER_LEDGER_LIST_FAILURE';

//...........Comp[leted Fancy Ledger]
export const complete_Ledger_Details_REQUEST = 'complete_Ledger_Details_REQUEST';
export const complete_Ledger_Details_SUCCESS = 'complete_Ledger_Details_SUCCESS';
export const complete_Ledger_Details_FAILURE = 'complete_Ledger_Details_FAILURE';



// User balance
export const USER_BALANCE_REQUEST = 'USER_BALANCE_REQUEST';
export const USER_BALANCE_SUCCESS = 'USER_BALANCE_SUCCESS';
export const USER_BALANCE_FAILURE = 'USER_BALANCE_FAILURE';
//updateRateReffrenece

export const UPDATE_RATE_REFFRENECE_REQUEST = 'UPDATE_RATE_REFFRENECE_REQUEST';
export const UPDATE_RATE_REFFRENECE_SUCCESS = 'UPDATE_RATE_REFFRENECE_SUCCESS';
export const UPDATE_RATE_REFFRENECE_FAILURE = 'UPDATE_RATE_REFFRENECE_FAILURE';


// casinoTransactionReport


export const CASINO_TRANSACTION_REPORT_REQUEST = 'CASINO_TRANSACTION_REPORT_REQUEST';
export const CASINO_TRANSACTION_REPORT_SUCCESS = 'CASINO_TRANSACTION_REPORT_SUCCESS';
export const CASINO_TRANSACTION_REPORT_FAILURE = 'CASINO_TRANSACTION_REPORT_FAILURE';

//casino/diamondBetsList
export const DIAMOND_BETS_LIST_REQUEST = 'DIAMOND_BETS_LIST_REQUEST';
export const DIAMOND_BETS_LIST_SUCCESS = 'DIAMOND_BETS_LIST_SUCCESS';
export const DIAMOND_BETS_LIST_FAILURE = 'DIAMOND_BETS_LIST_FAILURE';



//updateRateReffrenece

export const BET_PLACE_REQUEST = 'BET_PLACE_REQUEST';
export const BET_PLACE_SUCCESS = 'BET_PLACE_SUCCESS';
export const BET_PLACE_FAILURE = 'BET_PLACE_FAILURE';

//updateRateReffrenece

export const ODDS_BET_PLACE_REQUEST = 'ODDS_BET_PLACE_REQUEST';
export const ODDS_BET_PLACE_SUCCESS = 'ODDS_BET_PLACE_SUCCESS';
export const ODDS_BET_PLACE_FAILURE = 'ODDS_BET_PLACE_FAILURE';

// Casino Details By Event ID
export const CASINO_GET_DIAMOND_CASINO_BY_EVENT_ID_REQUEST = 'CASINO_GET_DIAMOND_CASINO_BY_EVENT_ID_REQUEST';
export const CASINO_GET_DIAMOND_CASINO_BY_EVENT_ID_SUCCESS = 'CASINO_GET_DIAMOND_CASINO_BY_EVENT_ID_SUCCESS';
export const CASINO_GET_DIAMOND_CASINO_BY_EVENT_ID_FAILURE = 'CASINO_GET_DIAMOND_CASINO_BY_EVENT_ID_FAILURE';

// CASINO CASINO BET PLACE

export const CASINO_CASINO_BET_PLACE_REQUEST = 'CASINO_CASINO_BET_PLACE_REQUEST';
export const CASINO_CASINO_BET_PLACE_SUCCESS = 'CASINO_CASINO_BET_PLACE_SUCCESS';
export const CASINO_CASINO_BET_PLACE_FAILURE = 'CASINO_CASINO_BET_PLACE_FAILURE';


// CASINO Login Url

export const CASINO_LOGIN_URL_REQUEST = 'CASINO_LOGIN_URL_REQUEST';
export const CASINO_LOGIN_URL_SUCCESS = 'CASINO_LOGIN_URL_SUCCESS';
export const CASINO_LOGIN_URL_FAILURE = 'CASINO_LOGIN_URL_FAILURE';

// 
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';

// ................. matka/getMatkaList

export const GET_MATKA_LIST_REQUEST = 'GET_MATKA_LIST_REQUEST';
export const GET_MATKA_LIST_SUCCESS = 'GET_MATKA_LIST_SUCCESS';
export const GET_MATKA_LIST_FAILURE = 'GET_MATKA_LIST_FAILURE';

export const GET_MATKA_BY_MATKA_EVENT_ID_REQUEST = 'GET_MATKA_BY_MATKA_EVENT_ID_REQUEST';
export const GET_MATKA_BY_MATKA_EVENT_ID_SUCCESS = 'GET_MATKA_BY_MATKA_EVENT_ID_SUCCESS';
export const GET_MATKA_BY_MATKA_EVENT_ID_FAILURE = 'GET_MATKA_BY_MATKA_EVENT_ID_FAILURE';

export const MATKA_BET_LIST_REQUEST = 'MATKA_BET_LIST_REQUEST';
export const MATKA_BET_LIST_SUCCESS = 'MATKA_BET_LIST_SUCCESS';
export const MATKA_BET_LIST_FAILURE = 'MATKA_BET_LIST_FAILURE';

export const CLOSE_ERROR_MODAL_MATCH_DETAIL = 'CLOSE_ERROR_MODAL_MATCH_DETAIL'

